name: Build macOS Installer

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release number for MW Agent for macOS'
        required: true
  push:
    paths-ignore:
      - '.github/**'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: arm64
            image: macos-latest
          - arch: amd64
            image: macos-12
      max-parallel: 1
    runs-on: ${{ matrix.image }}   
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GHCR_TOKEN }}
        ssh-key: ${{ secrets.CHECK_AGENT_ACCESS }}
        submodules: 'recursive'

    - name: Set up Git credentials
      run: |
        git config --global url."https://${{ secrets.GHCR_TOKEN }}:@github.com/".insteadOf "https://github.com/"
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.23.1'

    - name: Setting Release Number
      run: |
        if [ -n "${{ github.event.inputs.release_version }}" ]; then
          echo "RELEASE_VERSION=${{ github.event.inputs.release_version }}" >> $GITHUB_ENV
        else
          echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        fi

    - name: Build installer
      run: |
        CGO_ENABLED=1 GOPRIVATE=github.com/middleware-labs GOOS=darwin GOARCH=${{ matrix.arch }} go build -ldflags="-s -w -X main.agentVersion=${RELEASE_VERSION}" -v -a -o build/mw-host-agent cmd/host-agent/main.go
        bash package-tooling/darwin/create_installer.sh ${{ env.RELEASE_VERSION }}
      env:
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}

    - name: Upload installer package
      uses: actions/upload-artifact@v4
      with:
        name: mw-macos-agent-setup-${{ matrix.arch }}.pkg
        path: build/mw-macos-agent-setup-${{ matrix.arch }}.pkg
  
  upload-to-release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts

    - name: Set up GitHub CLI
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION="${{ github.event.inputs.release_version }}"
        if [ -z "$VERSION" ]; then
          VERSION="${GITHUB_REF#refs/tags/}"
        fi
        
        # Debug info
        echo "VERSION: $VERSION"
        echo "Artifacts directory content:"
        ls -R ./artifacts
        
        # For each architecture
        for arch in arm64 amd64; do
          echo "Processing $arch architecture"
          FILE="./artifacts/macos-installer-${arch}/mw-macos-agent-setup-${arch}.pkg"
          if [ -f "$FILE" ]; then
            echo "Uploading $FILE to release $VERSION"
            gh release upload "$VERSION" "$FILE" --clobber --repo ${{ github.repository }}
          else
            echo "Warning: $FILE not found"
            echo "Checking actual file path:"
            find ./artifacts -type f -name "*.pkg"
            # Try uploading with found path
            FOUND_FILE=$(find ./artifacts -type f -name "*.pkg" | grep "${arch}" | head -n 1)
            if [ ! -z "$FOUND_FILE" ]; then
              echo "Found file at $FOUND_FILE, attempting upload"
              gh release upload "$VERSION" "$FOUND_FILE" --clobber --repo ${{ github.repository }}
            fi
          fi
        done
